version: '3'
services:
  server:
    env_file:
      - .env
    container_name: hl-server
    image: hl-server:0.1.0
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
      args:
        - name=server
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - dev
    
  mongodb:
    container_name: hl-mongodb
    image: hl-mongodb:0.1.0
    build:
      context: ./
      dockerfile: ./docker/db/mongo/Dockerfile
      args:
        - name=mongodb
    depends_on:
      - server
    networks:
      - dev
    
  populate-db:
    container_name: hl-populate-db
    image: hl-populate-db:0.1.0
    build:
      context: ./
      dockerfile: ./docker/db/mongo/Dockerfile.populate
      args:
        - name=mongosh
    depends_on:
      - mongodb
    networks:
      - dev

  hl:
    env_file:
      - .env
    container_name: hl
    image: hl:0.1.0
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        - name=hl
    depends_on:
      - mongodb
    ports:
      - ${DEV_PORT}:${DEV_PORT}
    networks:
      - dev

networks:
  dev:
    ipam:
      config:
        - subnet: 172.16.1.0/16